# Generated by Django 5.1.4 on 2026-06-29 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('generic_name', models.CharField(blank=True, help_text='Salt / composition', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, help_text='e.g. Tablet (SR)', max_length=100)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500 mg', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. Anti-diabetic', max_length=100)),
                ('rx_required', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('how_it_works', models.TextField(blank=True)),
                ('uses', models.JSONField(blank=True, default=list)),
                ('side_effects', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenericAlternative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('save_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='medicines.medicine')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
