# Generated by Django 5.1.4 on 2026-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='smiles',
            field=models.CharField(blank=True, help_text="SMILES string (for the DDI model's fingerprints)", max_length=512),
        ),
    ]
