# Generated by Django 5.1.4 on 2026-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_medicine_smiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="how_it_works_hi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="how_it_works_mr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="side_effects_hi",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicine",
            name="side_effects_mr",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicine",
            name="uses_hi",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicine",
            name="uses_mr",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicine",
            name="warnings_hi",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicine",
            name="warnings_mr",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
