# Generated by Django 5.1.4 on 2026-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='reminder',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
