"""Seed demo medicines, generic alternatives and drug interactions.

Idempotent — safe to run multiple times. Usage: ``python manage.py seed_demo``.
"""
from django.core.management.base import BaseCommand

from apps.interactions.models import DrugInteraction
from apps.medicines.models import GenericAlternative, Medicine
from apps.medicines.smiles_data import lookup_smiles

MEDICINES = [
    {
        "name": "Glycomet 500 SR",
        "generic_name": "Metformin",
        "manufacturer": "USV Pvt Ltd",
        "form": "Tablet (SR)",
        "strength": "500 mg",
        "category": "Anti-diabetic",
        "rx_required": True,
        "price": "42.00",
        "how_it_works": "Lowers glucose production in the liver and helps your body respond to insulin more effectively.",
        "uses": ["Type 2 diabetes mellitus", "Improves insulin sensitivity", "PCOS (off-label)"],
        "side_effects": ["Nausea or upset stomach", "Metallic taste", "Low vitamin B12 over long-term use"],
        "warnings": ["Tell your doctor about kidney issues", "Avoid excess alcohol", "Pause before contrast scans"],
        "how_it_works_hi": "लीवर में ग्लूकोज़ उत्पादन को कम करता है और आपके शरीर को इंसुलिन के प्रति बेहतर प्रतिक्रिया देने में मदद करता है।",
        "uses_hi": ["टाइप 2 मधुमेह", "इंसुलिन संवेदनशीलता में सुधार", "PCOS (ऑफ-लेबल)"],
        "side_effects_hi": ["मतली या पेट खराब होना", "मुंह में धातु जैसा स्वाद", "लंबे समय तक उपयोग से विटामिन B12 की कमी"],
        "warnings_hi": ["अपने डॉक्टर को किडनी की समस्याओं के बारे में बताएं", "अधिक शराब से बचें", "कॉन्ट्रास्ट स्कैन से पहले रोकें"],
        "how_it_works_mr": "यकृतातील ग्लुकोज उत्पादन कमी करते आणि तुमच्या शरीराला इन्सुलिनला अधिक प्रभावीपणे प्रतिसाद देण्यास मदत करते.",
        "uses_mr": ["टाइप 2 मधुमेह", "इन्सुलिन संवेदनशीलता सुधारते", "PCOS (ऑफ-लेबल)"],
        "side_effects_mr": ["मळमळ किंवा पोट बिघडणे", "तोंडाला धातूसारखी चव", "दीर्घकाळ वापराने व्हिटॅमिन B12 ची कमतरता"],
        "warnings_mr": ["तुमच्या डॉक्टरांना किडनीच्या समस्यांबद्दल सांगा", "जास्त दारू टाळा", "कॉन्ट्रास्ट स्कॅनपूर्वी थांबा"],
        "alternatives": [
            {"name": "Metformin (generic)", "manufacturer": "Generic", "price": "12.00", "save_percent": 71},
            {"name": "Okamet 500", "manufacturer": "Cipla", "price": "38.00", "save_percent": 10},
            {"name": "Glyciphage", "manufacturer": "Franco-Indian", "price": "35.00", "save_percent": 17},
        ],
    },
    {
        "name": "Amlong 5", "generic_name": "Amlodipine", "manufacturer": "Micro Labs", "form": "Tablet",
        "strength": "5 mg", "category": "Anti-hypertensive", "rx_required": True, "price": "28.00",
        "how_it_works": "Relaxes and widens blood vessels by blocking calcium entry into vascular smooth muscle, lowering blood pressure and easing chest pain.",
        "uses": ["High blood pressure (hypertension)", "Chronic stable angina", "Coronary artery disease (off-label)"],
        "side_effects": ["Swelling in ankles or feet", "Dizziness or flushing", "Fatigue"],
        "warnings": ["Avoid grapefruit juice in large amounts", "Rise slowly from sitting/lying to avoid dizziness", "Tell your doctor about liver disease"],
        "how_it_works_hi": "रक्त वाहिकाओं की मांसपेशियों में कैल्शियम के प्रवेश को रोककर उन्हें आराम देता है और चौड़ा करता है, जिससे रक्तचाप कम होता है और सीने के दर्द में राहत मिलती है।",
        "uses_hi": ["उच्च रक्तचाप", "क्रॉनिक स्थिर एनजाइना", "कोरोनरी धमनी रोग (ऑफ-लेबल)"],
        "side_effects_hi": ["टखनों या पैरों में सूजन", "चक्कर आना या चेहरा लाल होना", "थकान"],
        "warnings_hi": ["अंगूर के रस का अधिक सेवन न करें", "चक्कर से बचने के लिए बैठने/लेटने से धीरे-धीरे उठें", "अपने डॉक्टर को लीवर की बीमारी के बारे में बताएं"],
        "how_it_works_mr": "रक्तवाहिन्यांच्या स्नायूंमध्ये कॅल्शियमचा प्रवेश रोखून त्यांना आराम देते आणि रुंद करते, ज्यामुळे रक्तदाब कमी होतो आणि छातीतील दुखणे कमी होते.",
        "uses_mr": ["उच्च रक्तदाब", "क्रॉनिक स्थिर एनजायना", "कोरोनरी धमनी रोग (ऑफ-लेबल)"],
        "side_effects_mr": ["घोट्यात किंवा पायात सूज", "चक्कर येणे किंवा चेहरा लाल होणे", "थकवा"],
        "warnings_mr": ["द्राक्षाचा रस जास्त प्रमाणात घेणे टाळा", "चक्कर टाळण्यासाठी बसून/झोपून हळूहळू उठा", "तुमच्या डॉक्टरांना यकृताच्या आजाराबद्दल सांगा"],
    },
    {
        "name": "Atorva 10", "generic_name": "Atorvastatin", "manufacturer": "Zydus", "form": "Tablet",
        "strength": "10 mg", "category": "Lipid-lowering", "rx_required": True, "price": "55.00",
        "how_it_works": "Blocks an enzyme the liver uses to make cholesterol, lowering LDL (\"bad\") cholesterol and triglycerides.",
        "uses": ["High cholesterol", "Reducing risk of heart attack and stroke", "Coronary heart disease prevention"],
        "side_effects": ["Muscle aches or weakness", "Mild digestive upset", "Headache"],
        "warnings": ["Report unexplained muscle pain immediately", "Avoid excess grapefruit juice", "Tell your doctor about liver problems or alcohol use"],
        "how_it_works_hi": "लीवर द्वारा कोलेस्ट्रॉल बनाने में उपयोग किए जाने वाले एक एंज़ाइम को रोकता है, जिससे LDL (\"खराब\") कोलेस्ट्रॉल और ट्राइग्लिसराइड्स कम होते हैं।",
        "uses_hi": ["उच्च कोलेस्ट्रॉल", "हृदयाघात और स्ट्रोक के जोखिम को कम करना", "कोरोनरी हृदय रोग की रोकथाम"],
        "side_effects_hi": ["मांसपेशियों में दर्द या कमज़ोरी", "हल्की पाचन संबंधी गड़बड़ी", "सिरदर्द"],
        "warnings_hi": ["अस्पष्टीकृत मांसपेशी दर्द की तुरंत सूचना दें", "अंगूर के रस के अधिक सेवन से बचें", "अपने डॉक्टर को लीवर की समस्याओं या शराब के सेवन के बारे में बताएं"],
        "how_it_works_mr": "यकृताद्वारे कोलेस्टेरॉल बनवण्यासाठी वापरल्या जाणाऱ्या एका एन्झाइमला रोखते, ज्यामुळे LDL (\"वाईट\") कोलेस्टेरॉल आणि ट्रायग्लिसराइड्स कमी होतात.",
        "uses_mr": ["उच्च कोलेस्टेरॉल", "हृदयविकाराचा झटका आणि स्ट्रोकचा धोका कमी करणे", "कोरोनरी हृदयरोग प्रतिबंध"],
        "side_effects_mr": ["स्नायू दुखणे किंवा अशक्तपणा", "सौम्य पचन समस्या", "डोकेदुखी"],
        "warnings_mr": ["अस्पष्ट स्नायू दुखण्याची तात्काळ माहिती द्या", "द्राक्षाचा रस जास्त प्रमाणात घेणे टाळा", "तुमच्या डॉक्टरांना यकृताच्या समस्या किंवा दारूच्या सेवनाबद्दल सांगा"],
    },
    {
        "name": "Pan 40", "generic_name": "Pantoprazole", "manufacturer": "Alkem", "form": "Tablet",
        "strength": "40 mg", "category": "Acid reducer", "rx_required": False, "price": "95.00",
        "how_it_works": "Reduces stomach acid production by blocking the proton pump in the stomach lining.",
        "uses": ["Acid reflux (GERD)", "Stomach ulcers", "Excess stomach acid conditions"],
        "side_effects": ["Headache", "Diarrhea or constipation", "Nausea"],
        "warnings": ["Long-term use may lower vitamin B12 or magnesium", "Take before a meal as directed", "Tell your doctor if used for more than a few weeks"],
        "how_it_works_hi": "पेट की परत में प्रोटॉन पंप को रोककर पेट में एसिड उत्पादन को कम करता है।",
        "uses_hi": ["एसिड रिफ्लक्स (GERD)", "पेट के अल्सर", "अधिक पेट एसिड की स्थितियां"],
        "side_effects_hi": ["सिरदर्द", "दस्त या कब्ज", "मतली"],
        "warnings_hi": ["लंबे समय तक उपयोग से विटामिन B12 या मैग्नीशियम कम हो सकता है", "निर्देशानुसार भोजन से पहले लें", "यदि कुछ हफ्तों से अधिक उपयोग करें तो अपने डॉक्टर को बताएं"],
        "how_it_works_mr": "पोटाच्या आतील थरातील प्रोटॉन पंप रोखून पोटातील आम्ल उत्पादन कमी करते.",
        "uses_mr": ["आम्ल रिफ्लक्स (GERD)", "पोटाचे व्रण", "जास्त पोटातील आम्लाच्या स्थिती"],
        "side_effects_mr": ["डोकेदुखी", "जुलाब किंवा बद्धकोष्ठता", "मळमळ"],
        "warnings_mr": ["दीर्घकाळ वापराने व्हिटॅमिन B12 किंवा मॅग्नेशियम कमी होऊ शकते", "सूचनेनुसार जेवणापूर्वी घ्या", "काही आठवड्यांपेक्षा जास्त वापरल्यास तुमच्या डॉक्टरांना सांगा"],
    },
    {
        "name": "Azithral 500", "generic_name": "Azithromycin", "manufacturer": "Alembic", "form": "Tablet",
        "strength": "500 mg", "category": "Antibiotic", "rx_required": True, "price": "118.00",
        "how_it_works": "Stops bacteria from producing proteins they need to grow and multiply.",
        "uses": ["Respiratory tract infections", "Ear and throat infections", "Skin infections"],
        "side_effects": ["Stomach upset or diarrhea", "Nausea", "Abdominal pain"],
        "warnings": ["Complete the full course even if you feel better", "Tell your doctor about heart rhythm problems", "Space apart from antacids"],
        "how_it_works_hi": "बैक्टीरिया को बढ़ने और गुणा करने के लिए आवश्यक प्रोटीन बनाने से रोकता है।",
        "uses_hi": ["श्वसन तंत्र संक्रमण", "कान और गले के संक्रमण", "त्वचा संक्रमण"],
        "side_effects_hi": ["पेट खराब होना या दस्त", "मतली", "पेट दर्द"],
        "warnings_hi": ["बेहतर महसूस होने पर भी पूरा कोर्स पूरा करें", "अपने डॉक्टर को हृदय की लय संबंधी समस्याओं के बारे में बताएं", "एंटासिड से समय का अंतर रखें"],
        "how_it_works_mr": "जीवाणूंना वाढण्यासाठी आणि गुणाकार करण्यासाठी आवश्यक प्रथिने तयार करण्यापासून रोखते.",
        "uses_mr": ["श्वसन मार्गाचे संसर्ग", "कान आणि घशाचे संसर्ग", "त्वचेचे संसर्ग"],
        "side_effects_mr": ["पोट बिघडणे किंवा जुलाब", "मळमळ", "पोटदुखी"],
        "warnings_mr": ["बरे वाटले तरी संपूर्ण कोर्स पूर्ण करा", "तुमच्या डॉक्टरांना हृदयाच्या तालाच्या समस्यांबद्दल सांगा", "अँटासिडपासून वेळेचे अंतर ठेवा"],
    },
    {
        "name": "Cetzine 10", "generic_name": "Cetirizine", "manufacturer": "Dr. Reddy's", "form": "Tablet",
        "strength": "10 mg", "category": "Anti-allergic", "rx_required": False, "price": "30.00",
        "how_it_works": "Blocks histamine, the chemical that causes allergy symptoms like itching, sneezing and runny nose.",
        "uses": ["Seasonal allergies (hay fever)", "Hives (urticaria)", "Itching from allergic skin reactions"],
        "side_effects": ["Drowsiness", "Dry mouth", "Headache"],
        "warnings": ["Avoid alcohol as it increases drowsiness", "Use caution when driving until you know how it affects you", "Tell your doctor about kidney problems"],
        "how_it_works_hi": "हिस्टामाइन को रोकता है, वह रसायन जो खुजली, छींक और नाक बहने जैसे एलर्जी लक्षणों का कारण बनता है।",
        "uses_hi": ["मौसमी एलर्जी (हे फीवर)", "पित्ती (उर्टिकेरिया)", "एलर्जी त्वचा प्रतिक्रियाओं से खुजली"],
        "side_effects_hi": ["उनींदापन", "मुंह सूखना", "सिरदर्द"],
        "warnings_hi": ["शराब से बचें क्योंकि यह उनींदापन बढ़ाती है", "जब तक पता न चले कि यह आपको कैसे प्रभावित करता है, ड्राइविंग में सावधानी बरतें", "अपने डॉक्टर को किडनी की समस्याओं के बारे में बताएं"],
        "how_it_works_mr": "हिस्टामाइन रोखते, हे रसायन ज्यामुळे खाज, शिंका आणि नाक वाहणे यासारखी ऍलर्जीची लक्षणे होतात.",
        "uses_mr": ["हंगामी ऍलर्जी (हे फिव्हर)", "अंगावर उठणाऱ्या पित्ताच्या गाठी (उर्टिकेरिया)", "ऍलर्जीक त्वचा प्रतिक्रियांमुळे खाज"],
        "side_effects_mr": ["झोप येणे", "तोंड कोरडे पडणे", "डोकेदुखी"],
        "warnings_mr": ["दारू टाळा कारण ती झोप वाढवते", "हे तुमच्यावर कसा परिणाम करते हे कळेपर्यंत वाहन चालवताना काळजी घ्या", "तुमच्या डॉक्टरांना किडनीच्या समस्यांबद्दल सांगा"],
    },
    # More real medicines (valid SMILES) for interaction-checker testing.
    {
        "name": "Dolo 650", "generic_name": "Paracetamol", "manufacturer": "Micro Labs", "form": "Tablet",
        "strength": "650 mg", "category": "Analgesic", "rx_required": False, "price": "31.00", "smiles": "CC(=O)Nc1ccc(O)cc1",
        "how_it_works": "Reduces pain and fever by acting on the brain's temperature-regulation and pain centers.",
        "uses": ["Fever", "Mild to moderate pain", "Headache and body ache"],
        "side_effects": ["Rare at recommended doses", "Nausea (uncommon)", "Allergic skin reaction (rare)"],
        "warnings": ["Never exceed the maximum daily dose", "Avoid combining with other paracetamol-containing products", "Tell your doctor about liver disease or heavy alcohol use"],
        "how_it_works_hi": "मस्तिष्क के तापमान-नियमन और दर्द केंद्रों पर कार्य करके दर्द और बुखार को कम करता है।",
        "uses_hi": ["बुखार", "हल्का से मध्यम दर्द", "सिरदर्द और शरीर दर्द"],
        "side_effects_hi": ["अनुशंसित खुराक पर दुर्लभ", "मतली (असामान्य)", "एलर्जी त्वचा प्रतिक्रिया (दुर्लभ)"],
        "warnings_hi": ["अधिकतम दैनिक खुराक कभी न बढ़ाएं", "अन्य पैरासिटामोल युक्त उत्पादों के साथ न मिलाएं", "अपने डॉक्टर को लीवर की बीमारी या अधिक शराब सेवन के बारे में बताएं"],
        "how_it_works_mr": "मेंदूच्या तापमान-नियमन आणि वेदना केंद्रांवर कार्य करून वेदना आणि ताप कमी करते.",
        "uses_mr": ["ताप", "सौम्य ते मध्यम वेदना", "डोकेदुखी आणि अंगदुखी"],
        "side_effects_mr": ["शिफारस केलेल्या डोसवर दुर्मिळ", "मळमळ (असामान्य)", "ऍलर्जीक त्वचा प्रतिक्रिया (दुर्मिळ)"],
        "warnings_mr": ["कमाल दैनंदिन डोस कधीही ओलांडू नका", "इतर पॅरासिटामॉलयुक्त उत्पादनांसोबत एकत्र करू नका", "तुमच्या डॉक्टरांना यकृताच्या आजाराबद्दल किंवा जास्त दारू सेवनाबद्दल सांगा"],
    },
    {
        "name": "Brufen 400", "generic_name": "Ibuprofen", "manufacturer": "Abbott", "form": "Tablet",
        "strength": "400 mg", "category": "NSAID", "rx_required": False, "price": "28.00", "smiles": "CC(C)Cc1ccc(cc1)C(C)C(=O)O",
        "how_it_works": "Blocks enzymes (COX) that produce chemicals causing pain, fever and inflammation.",
        "uses": ["Pain relief", "Fever", "Inflammation (e.g. sprains, arthritis)"],
        "side_effects": ["Stomach upset or heartburn", "Nausea", "Dizziness"],
        "warnings": ["Take with food to reduce stomach irritation", "Avoid if you have stomach ulcers or kidney disease", "Don't combine with other NSAIDs"],
        "how_it_works_hi": "उन एंज़ाइम्स (COX) को रोकता है जो दर्द, बुखार और सूजन पैदा करने वाले रसायन बनाते हैं।",
        "uses_hi": ["दर्द से राहत", "बुखार", "सूजन (जैसे मोच, गठिया)"],
        "side_effects_hi": ["पेट खराब होना या सीने में जलन", "मतली", "चक्कर आना"],
        "warnings_hi": ["पेट की जलन कम करने के लिए भोजन के साथ लें", "यदि आपको पेट के अल्सर या किडनी की बीमारी है तो बचें", "अन्य NSAIDs के साथ न मिलाएं"],
        "how_it_works_mr": "वेदना, ताप आणि सूज निर्माण करणारी रसायने तयार करणाऱ्या एन्झाइम्स (COX) ला रोखते.",
        "uses_mr": ["वेदना आराम", "ताप", "सूज (उदा. मुरगळणे, संधिवात)"],
        "side_effects_mr": ["पोट बिघडणे किंवा छातीत जळजळ", "मळमळ", "चक्कर येणे"],
        "warnings_mr": ["पोटाची जळजळ कमी करण्यासाठी अन्नासोबत घ्या", "पोटात व्रण किंवा किडनीचा आजार असल्यास टाळा", "इतर NSAIDs सोबत एकत्र करू नका"],
    },
    {
        "name": "Ecosprin 75", "generic_name": "Aspirin", "manufacturer": "USV", "form": "Tablet",
        "strength": "75 mg", "category": "Antiplatelet", "rx_required": False, "price": "10.00", "smiles": "CC(=O)Oc1ccccc1C(=O)O",
        "how_it_works": "Prevents platelets in the blood from clumping together, reducing the risk of clots.",
        "uses": ["Prevention of heart attack and stroke", "Reducing blood clot risk in heart disease", "Mild pain relief (higher doses)"],
        "side_effects": ["Stomach irritation", "Increased bleeding tendency", "Heartburn"],
        "warnings": ["Increases bleeding risk, especially with other blood thinners", "Take with food", "Tell your doctor before any surgery or dental work"],
        "how_it_works_hi": "रक्त में प्लेटलेट्स को एक साथ जमने से रोकता है, जिससे थक्कों का जोखिम कम होता है।",
        "uses_hi": ["हृदयाघात और स्ट्रोक की रोकथाम", "हृदय रोग में रक्त के थक्के के जोखिम को कम करना", "हल्के दर्द से राहत (उच्च खुराक)"],
        "side_effects_hi": ["पेट में जलन", "रक्तस्राव की बढ़ी हुई प्रवृत्ति", "सीने में जलन"],
        "warnings_hi": ["रक्तस्राव के जोखिम को बढ़ाता है, खासकर अन्य ब्लड थिनर के साथ", "भोजन के साथ लें", "किसी भी सर्जरी या दंत चिकित्सा से पहले अपने डॉक्टर को बताएं"],
        "how_it_works_mr": "रक्तातील प्लेटलेट्स एकत्र जमण्यापासून रोखते, ज्यामुळे गुठळ्यांचा धोका कमी होतो.",
        "uses_mr": ["हृदयविकाराचा झटका आणि स्ट्रोकचा प्रतिबंध", "हृदयरोगात रक्ताच्या गुठळ्यांचा धोका कमी करणे", "सौम्य वेदना आराम (जास्त डोस)"],
        "side_effects_mr": ["पोटात जळजळ", "रक्तस्रावाची वाढलेली प्रवृत्ती", "छातीत जळजळ"],
        "warnings_mr": ["रक्तस्रावाचा धोका वाढवते, विशेषतः इतर रक्त पातळ करणाऱ्या औषधांसोबत", "अन्नासोबत घ्या", "कोणत्याही शस्त्रक्रिया किंवा दंत उपचारापूर्वी तुमच्या डॉक्टरांना सांगा"],
    },
    {
        "name": "Omez", "generic_name": "Omeprazole", "manufacturer": "Dr. Reddy's", "form": "Capsule",
        "strength": "20 mg", "category": "Acid reducer", "rx_required": False, "price": "58.00", "smiles": "COc1ccc2[nH]c(S(=O)Cc3ncc(C)c(OC)c3C)nc2c1",
        "how_it_works": "Reduces stomach acid production by blocking the proton pump in the stomach lining.",
        "uses": ["Acid reflux (GERD)", "Stomach and duodenal ulcers", "Excess stomach acid conditions"],
        "side_effects": ["Headache", "Diarrhea", "Stomach pain"],
        "warnings": ["Long-term use may lower vitamin B12 or magnesium", "Take before a meal as directed", "May reduce effectiveness of some other medicines (e.g. clopidogrel)"],
        "how_it_works_hi": "पेट की परत में प्रोटॉन पंप को रोककर पेट में एसिड उत्पादन को कम करता है।",
        "uses_hi": ["एसिड रिफ्लक्स (GERD)", "पेट और ड्यूओडेनल अल्सर", "अधिक पेट एसिड की स्थितियां"],
        "side_effects_hi": ["सिरदर्द", "दस्त", "पेट दर्द"],
        "warnings_hi": ["लंबे समय तक उपयोग से विटामिन B12 या मैग्नीशियम कम हो सकता है", "निर्देशानुसार भोजन से पहले लें", "कुछ अन्य दवाओं (जैसे क्लोपिडोग्रेल) की प्रभावशीलता कम कर सकता है"],
        "how_it_works_mr": "पोटाच्या आतील थरातील प्रोटॉन पंप रोखून पोटातील आम्ल उत्पादन कमी करते.",
        "uses_mr": ["आम्ल रिफ्लक्स (GERD)", "पोट आणि ड्युओडेनल व्रण", "जास्त पोटातील आम्लाच्या स्थिती"],
        "side_effects_mr": ["डोकेदुखी", "जुलाब", "पोटदुखी"],
        "warnings_mr": ["दीर्घकाळ वापराने व्हिटॅमिन B12 किंवा मॅग्नेशियम कमी होऊ शकते", "सूचनेनुसार जेवणापूर्वी घ्या", "काही इतर औषधांची (उदा. क्लोपिडोग्रेल) परिणामकारकता कमी करू शकते"],
    },
    {
        "name": "Ciplox 500", "generic_name": "Ciprofloxacin", "manufacturer": "Cipla", "form": "Tablet",
        "strength": "500 mg", "category": "Antibiotic", "rx_required": True, "price": "72.00", "smiles": "OC(=O)C1=CN(C2CC2)c2cc(N3CCNCC3)c(F)cc2C1=O",
        "how_it_works": "Kills bacteria by blocking enzymes they need to copy their DNA.",
        "uses": ["Urinary tract infections", "Bacterial gastroenteritis", "Respiratory and skin infections"],
        "side_effects": ["Nausea", "Diarrhea", "Dizziness"],
        "warnings": ["May cause tendon problems, especially in older adults", "Avoid excess sun exposure", "Space apart from antacids and dairy"],
        "how_it_works_hi": "बैक्टीरिया को उनके DNA की प्रतिलिपि बनाने के लिए आवश्यक एंज़ाइम्स को रोककर मारता है।",
        "uses_hi": ["मूत्र मार्ग संक्रमण", "बैक्टीरियल गैस्ट्रोएंटेराइटिस", "श्वसन और त्वचा संक्रमण"],
        "side_effects_hi": ["मतली", "दस्त", "चक्कर आना"],
        "warnings_hi": ["टेंडन की समस्याएं हो सकती हैं, खासकर बुज़ुर्गों में", "अधिक धूप में रहने से बचें", "एंटासिड और डेयरी से समय का अंतर रखें"],
        "how_it_works_mr": "जीवाणूंना त्यांच्या DNA ची प्रत बनवण्यासाठी आवश्यक एन्झाइम्स रोखून मारते.",
        "uses_mr": ["मूत्रमार्गाचे संसर्ग", "बॅक्टेरियल गॅस्ट्रोएंटेरायटिस", "श्वसन आणि त्वचेचे संसर्ग"],
        "side_effects_mr": ["मळमळ", "जुलाब", "चक्कर येणे"],
        "warnings_mr": ["टेंडनच्या समस्या होऊ शकतात, विशेषतः वृद्धांमध्ये", "जास्त उन्हात राहणे टाळा", "अँटासिड आणि दुग्धजन्य पदार्थांपासून वेळेचे अंतर ठेवा"],
    },
    {
        "name": "Losar 50", "generic_name": "Losartan", "manufacturer": "Unichem", "form": "Tablet",
        "strength": "50 mg", "category": "Anti-hypertensive", "rx_required": True, "price": "45.00", "smiles": "CCCCc1nc(Cl)c(CO)n1Cc1ccc(-c2ccccc2-c2nnn[nH]2)cc1",
        "how_it_works": "Blocks a hormone (angiotensin II) that narrows blood vessels, helping them relax and lowering blood pressure.",
        "uses": ["High blood pressure", "Protecting kidneys in diabetes", "Heart failure (as advised by doctor)"],
        "side_effects": ["Dizziness", "Fatigue", "Higher potassium levels (rare)"],
        "warnings": ["Tell your doctor if you're pregnant or planning pregnancy", "Avoid potassium supplements unless advised", "Regular blood pressure and kidney monitoring recommended"],
        "how_it_works_hi": "एक हार्मोन (एंजियोटेंसिन II) को रोकता है जो रक्त वाहिकाओं को संकुचित करता है, जिससे वे आराम करती हैं और रक्तचाप कम होता है।",
        "uses_hi": ["उच्च रक्तचाप", "मधुमेह में किडनी की सुरक्षा", "हृदय विफलता (डॉक्टर की सलाह अनुसार)"],
        "side_effects_hi": ["चक्कर आना", "थकान", "पोटैशियम का उच्च स्तर (दुर्लभ)"],
        "warnings_hi": ["यदि आप गर्भवती हैं या गर्भधारण की योजना बना रही हैं तो अपने डॉक्टर को बताएं", "सलाह के बिना पोटैशियम सप्लीमेंट से बचें", "नियमित रक्तचाप और किडनी की निगरानी की सलाह दी जाती है"],
        "how_it_works_mr": "रक्तवाहिन्या आकुंचित करणाऱ्या एका हार्मोनला (अँजिओटेन्सिन II) रोखते, ज्यामुळे त्या आराम करतात आणि रक्तदाब कमी होतो.",
        "uses_mr": ["उच्च रक्तदाब", "मधुमेहात किडनीचे संरक्षण", "हृदय विफलता (डॉक्टरांच्या सल्ल्यानुसार)"],
        "side_effects_mr": ["चक्कर येणे", "थकवा", "पोटॅशियमची उच्च पातळी (दुर्मिळ)"],
        "warnings_mr": ["तुम्ही गर्भवती असाल किंवा गर्भधारणेचे नियोजन करत असाल तर तुमच्या डॉक्टरांना सांगा", "सल्ल्याशिवाय पोटॅशियम सप्लिमेंट्स टाळा", "नियमित रक्तदाब आणि किडनी तपासणीची शिफारस केली जाते"],
    },
    {
        "name": "Metolar 50", "generic_name": "Metoprolol", "manufacturer": "Cipla", "form": "Tablet",
        "strength": "50 mg", "category": "Beta-blocker", "rx_required": True, "price": "40.00", "smiles": "CC(C)NCC(O)COc1ccc(CCOC)cc1",
        "how_it_works": "Blocks adrenaline's effect on the heart, slowing heart rate and lowering blood pressure.",
        "uses": ["High blood pressure", "Chest pain (angina)", "Irregular heart rhythms"],
        "side_effects": ["Fatigue", "Cold hands or feet", "Dizziness"],
        "warnings": ["Don't stop suddenly — taper under medical guidance", "Tell your doctor about asthma or breathing conditions", "May mask signs of low blood sugar in diabetics"],
        "how_it_works_hi": "हृदय पर एड्रेनालिन के प्रभाव को रोकता है, हृदय गति को धीमा करता है और रक्तचाप कम करता है।",
        "uses_hi": ["उच्च रक्तचाप", "सीने में दर्द (एनजाइना)", "अनियमित हृदय गति"],
        "side_effects_hi": ["थकान", "हाथ या पैर ठंडे होना", "चक्कर आना"],
        "warnings_hi": ["अचानक बंद न करें — चिकित्सकीय मार्गदर्शन में धीरे-धीरे कम करें", "अपने डॉक्टर को अस्थमा या सांस की स्थितियों के बारे में बताएं", "मधुमेह रोगियों में निम्न रक्त शर्करा के लक्षणों को छिपा सकता है"],
        "how_it_works_mr": "हृदयावरील एड्रेनालिनचा प्रभाव रोखते, हृदयाची गती मंदावते आणि रक्तदाब कमी करते.",
        "uses_mr": ["उच्च रक्तदाब", "छातीत दुखणे (एनजायना)", "अनियमित हृदयगती"],
        "side_effects_mr": ["थकवा", "हात किंवा पाय थंड पडणे", "चक्कर येणे"],
        "warnings_mr": ["अचानक बंद करू नका — वैद्यकीय मार्गदर्शनाखाली हळूहळू कमी करा", "तुमच्या डॉक्टरांना दमा किंवा श्वसनाच्या समस्यांबद्दल सांगा", "मधुमेही रुग्णांमध्ये कमी रक्तशर्करेची लक्षणे लपवू शकते"],
    },
    {
        "name": "Mox 500", "generic_name": "Amoxicillin", "manufacturer": "Sun Pharma", "form": "Capsule",
        "strength": "500 mg", "category": "Antibiotic", "rx_required": True, "price": "65.00", "smiles": "CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O",
        "how_it_works": "Weakens bacterial cell walls, causing the bacteria to burst and die.",
        "uses": ["Respiratory tract infections", "Ear infections", "Urinary tract infections"],
        "side_effects": ["Diarrhea", "Nausea", "Skin rash"],
        "warnings": ["Complete the full course even if you feel better", "Tell your doctor about penicillin allergy", "May reduce effectiveness of some contraceptive pills"],
        "how_it_works_hi": "बैक्टीरिया की कोशिका भित्ति को कमज़ोर करता है, जिससे बैक्टीरिया फट कर मर जाते हैं।",
        "uses_hi": ["श्वसन तंत्र संक्रमण", "कान के संक्रमण", "मूत्र मार्ग संक्रमण"],
        "side_effects_hi": ["दस्त", "मतली", "त्वचा पर चकत्ते"],
        "warnings_hi": ["बेहतर महसूस होने पर भी पूरा कोर्स पूरा करें", "अपने डॉक्टर को पेनिसिलिन एलर्जी के बारे में बताएं", "कुछ गर्भनिरोधक गोलियों की प्रभावशीलता कम कर सकता है"],
        "how_it_works_mr": "जीवाणूंच्या पेशीभित्तिका कमकुवत करते, ज्यामुळे जीवाणू फुटून मरतात.",
        "uses_mr": ["श्वसन मार्गाचे संसर्ग", "कानाचे संसर्ग", "मूत्रमार्गाचे संसर्ग"],
        "side_effects_mr": ["जुलाब", "मळमळ", "त्वचेवर पुरळ"],
        "warnings_mr": ["बरे वाटले तरी संपूर्ण कोर्स पूर्ण करा", "तुमच्या डॉक्टरांना पेनिसिलिन ऍलर्जीबद्दल सांगा", "काही गर्भनिरोधक गोळ्यांची परिणामकारकता कमी करू शकते"],
    },
    {
        "name": "Voveran 50", "generic_name": "Diclofenac", "manufacturer": "Novartis", "form": "Tablet",
        "strength": "50 mg", "category": "NSAID", "rx_required": True, "price": "22.00", "smiles": "OC(=O)Cc1ccccc1Nc1c(Cl)cccc1Cl",
        "how_it_works": "Blocks enzymes (COX) that produce chemicals causing pain, fever and inflammation.",
        "uses": ["Pain relief", "Inflammation (arthritis, sprains)", "Post-operative or menstrual pain"],
        "side_effects": ["Stomach upset", "Heartburn", "Headache"],
        "warnings": ["Take with food to reduce stomach irritation", "Avoid if you have heart, kidney or stomach ulcer disease", "Increases bleeding risk with blood thinners like warfarin"],
        "how_it_works_hi": "उन एंज़ाइम्स (COX) को रोकता है जो दर्द, बुखार और सूजन पैदा करने वाले रसायन बनाते हैं।",
        "uses_hi": ["दर्द से राहत", "सूजन (गठिया, मोच)", "ऑपरेशन के बाद या मासिक धर्म का दर्द"],
        "side_effects_hi": ["पेट खराब होना", "सीने में जलन", "सिरदर्द"],
        "warnings_hi": ["पेट की जलन कम करने के लिए भोजन के साथ लें", "यदि आपको हृदय, किडनी या पेट के अल्सर की बीमारी है तो बचें", "वारफारिन जैसे ब्लड थिनर के साथ रक्तस्राव के जोखिम को बढ़ाता है"],
        "how_it_works_mr": "वेदना, ताप आणि सूज निर्माण करणारी रसायने तयार करणाऱ्या एन्झाइम्स (COX) ला रोखते.",
        "uses_mr": ["वेदना आराम", "सूज (संधिवात, मुरगळणे)", "शस्त्रक्रियेनंतरचे किंवा मासिक पाळीतील दुखणे"],
        "side_effects_mr": ["पोट बिघडणे", "छातीत जळजळ", "डोकेदुखी"],
        "warnings_mr": ["पोटाची जळजळ कमी करण्यासाठी अन्नासोबत घ्या", "हृदय, किडनी किंवा पोटात व्रणाचा आजार असल्यास टाळा", "वॉरफेरिनसारख्या रक्त पातळ करणाऱ्या औषधांसोबत रक्तस्रावाचा धोका वाढवते"],
    },
    {
        "name": "Deplatt 75", "generic_name": "Clopidogrel", "manufacturer": "Torrent", "form": "Tablet",
        "strength": "75 mg", "category": "Antiplatelet", "rx_required": True, "price": "88.00", "smiles": "COC(=O)C(c1ccccc1Cl)N1CCc2sccc2C1",
        "how_it_works": "Prevents platelets in the blood from clumping together, reducing the risk of clots.",
        "uses": ["Prevention of heart attack and stroke", "After stent placement", "Peripheral artery disease"],
        "side_effects": ["Increased bleeding or bruising", "Stomach upset", "Headache"],
        "warnings": ["Tell your doctor before any surgery or dental work", "Avoid certain acid reducers (e.g. omeprazole) without medical advice", "Report unusual bleeding immediately"],
        "how_it_works_hi": "रक्त में प्लेटलेट्स को एक साथ जमने से रोकता है, जिससे थक्कों का जोखिम कम होता है।",
        "uses_hi": ["हृदयाघात और स्ट्रोक की रोकथाम", "स्टेंट लगाने के बाद", "पेरिफेरल आर्टरी रोग"],
        "side_effects_hi": ["रक्तस्राव या चोट के निशान बढ़ना", "पेट खराब होना", "सिरदर्द"],
        "warnings_hi": ["किसी भी सर्जरी या दंत चिकित्सा से पहले अपने डॉक्टर को बताएं", "चिकित्सकीय सलाह के बिना कुछ एसिड कम करने वाली दवाओं (जैसे ओमेप्राज़ोल) से बचें", "असामान्य रक्तस्राव की तुरंत सूचना दें"],
        "how_it_works_mr": "रक्तातील प्लेटलेट्स एकत्र जमण्यापासून रोखते, ज्यामुळे गुठळ्यांचा धोका कमी होतो.",
        "uses_mr": ["हृदयविकाराचा झटका आणि स्ट्रोकचा प्रतिबंध", "स्टेंट बसवल्यानंतर", "पेरिफेरल आर्टरी आजार"],
        "side_effects_mr": ["रक्तस्राव किंवा जखमांचे डाग वाढणे", "पोट बिघडणे", "डोकेदुखी"],
        "warnings_mr": ["कोणत्याही शस्त्रक्रिया किंवा दंत उपचारापूर्वी तुमच्या डॉक्टरांना सांगा", "वैद्यकीय सल्ल्याशिवाय काही आम्ल कमी करणारी औषधे (उदा. ओमेप्राझोल) टाळा", "असामान्य रक्तस्रावाची तात्काळ माहिती द्या"],
    },
    {
        "name": "Lasix 40", "generic_name": "Furosemide", "manufacturer": "Sanofi", "form": "Tablet",
        "strength": "40 mg", "category": "Diuretic", "rx_required": True, "price": "18.00", "smiles": "NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl",
        "how_it_works": "Makes the kidneys remove more salt and water into urine, reducing fluid buildup and blood pressure.",
        "uses": ["Fluid retention (edema)", "High blood pressure", "Heart failure"],
        "side_effects": ["Increased urination", "Dizziness", "Low potassium levels"],
        "warnings": ["Monitor blood pressure and electrolytes regularly", "Rise slowly to avoid dizziness", "Tell your doctor about kidney or hearing problems"],
        "how_it_works_hi": "किडनी को मूत्र में अधिक नमक और पानी निकालने पर मजबूर करता है, जिससे तरल पदार्थ का जमाव और रक्तचाप कम होता है।",
        "uses_hi": ["तरल पदार्थ का जमाव (एडिमा)", "उच्च रक्तचाप", "हृदय विफलता"],
        "side_effects_hi": ["अधिक पेशाब आना", "चक्कर आना", "पोटैशियम का निम्न स्तर"],
        "warnings_hi": ["नियमित रूप से रक्तचाप और इलेक्ट्रोलाइट्स की निगरानी करें", "चक्कर से बचने के लिए धीरे-धीरे उठें", "अपने डॉक्टर को किडनी या सुनने की समस्याओं के बारे में बताएं"],
        "how_it_works_mr": "किडनीला लघवीत जास्त मीठ आणि पाणी बाहेर टाकण्यास भाग पाडते, ज्यामुळे द्रव साठा आणि रक्तदाब कमी होतो.",
        "uses_mr": ["द्रव साठणे (एडिमा)", "उच्च रक्तदाब", "हृदय विफलता"],
        "side_effects_mr": ["जास्त लघवी होणे", "चक्कर येणे", "पोटॅशियमची कमी पातळी"],
        "warnings_mr": ["नियमितपणे रक्तदाब आणि इलेक्ट्रोलाइट्सची तपासणी करा", "चक्कर टाळण्यासाठी हळूहळू उठा", "तुमच्या डॉक्टरांना किडनी किंवा ऐकण्याच्या समस्यांबद्दल सांगा"],
    },
    {
        "name": "Gabapin 300", "generic_name": "Gabapentin", "manufacturer": "Intas", "form": "Capsule",
        "strength": "300 mg", "category": "Anticonvulsant", "rx_required": True, "price": "96.00", "smiles": "OC(=O)CC1(CN)CCCCC1",
        "how_it_works": "Calms overactive nerve signals in the brain and nerves, reducing seizures and nerve pain.",
        "uses": ["Nerve pain (neuropathy)", "Seizure disorders (epilepsy)", "Restless legs syndrome (off-label)"],
        "side_effects": ["Drowsiness", "Dizziness", "Fatigue"],
        "warnings": ["Don't stop suddenly — taper under medical guidance", "Use caution when driving until you know how it affects you", "Tell your doctor about kidney problems"],
        "how_it_works_hi": "मस्तिष्क और नसों में अतिसक्रिय तंत्रिका संकेतों को शांत करता है, जिससे दौरे और नसों के दर्द में कमी आती है।",
        "uses_hi": ["नसों का दर्द (न्यूरोपैथी)", "दौरे संबंधी विकार (मिर्गी)", "रेस्टलेस लेग्स सिंड्रोम (ऑफ-लेबल)"],
        "side_effects_hi": ["उनींदापन", "चक्कर आना", "थकान"],
        "warnings_hi": ["अचानक बंद न करें — चिकित्सकीय मार्गदर्शन में धीरे-धीरे कम करें", "जब तक पता न चले कि यह आपको कैसे प्रभावित करता है, ड्राइविंग में सावधानी बरतें", "अपने डॉक्टर को किडनी की समस्याओं के बारे में बताएं"],
        "how_it_works_mr": "मेंदू आणि नसांमधील अतिसक्रिय संदेशांना शांत करते, ज्यामुळे झटके आणि नसांचे दुखणे कमी होते.",
        "uses_mr": ["नसांचे दुखणे (न्यूरोपॅथी)", "झटक्यांचे विकार (एपिलेप्सी)", "रेस्टलेस लेग्स सिंड्रोम (ऑफ-लेबल)"],
        "side_effects_mr": ["झोप येणे", "चक्कर येणे", "थकवा"],
        "warnings_mr": ["अचानक बंद करू नका — वैद्यकीय मार्गदर्शनाखाली हळूहळू कमी करा", "हे तुमच्यावर कसा परिणाम करते हे कळेपर्यंत वाहन चालवताना काळजी घ्या", "तुमच्या डॉक्टरांना किडनीच्या समस्यांबद्दल सांगा"],
    },
    {
        "name": "Asthalin", "generic_name": "Salbutamol", "manufacturer": "Cipla", "form": "Inhaler",
        "strength": "100 mcg", "category": "Bronchodilator", "rx_required": True, "price": "130.00", "smiles": "CC(C)(C)NCC(O)c1ccc(O)c(CO)c1",
        "how_it_works": "Relaxes the muscles around the airways, making it easier to breathe.",
        "uses": ["Asthma", "Wheezing and breathlessness", "Chronic obstructive pulmonary disease (COPD)"],
        "side_effects": ["Tremor (shakiness)", "Fast heartbeat", "Headache"],
        "warnings": ["Don't exceed the prescribed number of puffs", "Seek help if it's not relieving symptoms", "Tell your doctor about heart conditions"],
        "how_it_works_hi": "वायुमार्ग के आसपास की मांसपेशियों को आराम देता है, जिससे सांस लेना आसान हो जाता है।",
        "uses_hi": ["अस्थमा", "घरघराहट और सांस फूलना", "क्रॉनिक ऑब्सट्रक्टिव पल्मोनरी डिज़ीज़ (COPD)"],
        "side_effects_hi": ["कंपन (कांपना)", "तेज़ दिल की धड़कन", "सिरदर्द"],
        "warnings_hi": ["निर्धारित पफ की संख्या से अधिक न लें", "यदि यह लक्षणों से राहत नहीं देता है तो सहायता लें", "अपने डॉक्टर को हृदय की स्थितियों के बारे में बताएं"],
        "how_it_works_mr": "श्वासनलिकांभोवतीच्या स्नायूंना आराम देते, ज्यामुळे श्वास घेणे सोपे होते.",
        "uses_mr": ["दमा", "घरघर आणि श्वास फुलणे", "क्रॉनिक ऑब्स्ट्रक्टिव्ह पल्मनरी डिसीज (COPD)"],
        "side_effects_mr": ["कंप (थरथरणे)", "जलद हृदयगती", "डोकेदुखी"],
        "warnings_mr": ["सांगितलेल्या पफच्या संख्येपेक्षा जास्त घेऊ नका", "जर लक्षणे कमी होत नसतील तर मदत घ्या", "तुमच्या डॉक्टरांना हृदयाच्या स्थितींबद्दल सांगा"],
    },
    {
        "name": "Warf 5", "generic_name": "Warfarin", "manufacturer": "Cipla", "form": "Tablet",
        "strength": "5 mg", "category": "Anticoagulant", "rx_required": True, "price": "42.00", "smiles": "CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O",
        "how_it_works": "Blocks the liver's production of clotting factors, thinning the blood and preventing clots.",
        "uses": ["Prevention of blood clots", "Atrial fibrillation", "After heart valve replacement"],
        "side_effects": ["Increased bleeding or bruising", "Nosebleeds", "Blood in urine or stool (report immediately)"],
        "warnings": ["Requires regular blood tests (INR) to monitor dose", "Keep vitamin K intake consistent (leafy greens)", "Tell your doctor before any surgery, dental work or new medicine"],
        "how_it_works_hi": "लीवर द्वारा थक्का जमाने वाले कारकों के उत्पादन को रोकता है, रक्त को पतला करता है और थक्कों को रोकता है।",
        "uses_hi": ["रक्त के थक्कों की रोकथाम", "आलिंद फिब्रिलेशन", "हृदय वाल्व बदलने के बाद"],
        "side_effects_hi": ["रक्तस्राव या चोट के निशान बढ़ना", "नाक से खून आना", "पेशाब या मल में खून (तुरंत सूचित करें)"],
        "warnings_hi": ["खुराक की निगरानी के लिए नियमित रक्त परीक्षण (INR) आवश्यक है", "विटामिन K का सेवन सुसंगत रखें (हरी पत्तेदार सब्जियां)", "किसी भी सर्जरी, दंत चिकित्सा या नई दवा से पहले अपने डॉक्टर को बताएं"],
        "how_it_works_mr": "यकृताद्वारे गुठळी तयार करणाऱ्या घटकांचे उत्पादन रोखते, रक्त पातळ करते आणि गुठळ्या रोखते.",
        "uses_mr": ["रक्ताच्या गुठळ्यांचा प्रतिबंध", "अॅट्रियल फायब्रिलेशन", "हृदय झडप बदलल्यानंतर"],
        "side_effects_mr": ["रक्तस्राव किंवा जखमांचे डाग वाढणे", "नाकातून रक्त येणे", "लघवी किंवा विष्ठेत रक्त (तात्काळ माहिती द्या)"],
        "warnings_mr": ["डोसच्या देखरेखीसाठी नियमित रक्त तपासणी (INR) आवश्यक आहे", "व्हिटॅमिन K चे सेवन सातत्यपूर्ण ठेवा (हिरव्या पालेभाज्या)", "कोणत्याही शस्त्रक्रिया, दंत उपचार किंवा नवीन औषधापूर्वी तुमच्या डॉक्टरांना सांगा"],
    },
]

INTERACTIONS = [
    {
        "a": "Atorva 10", "b": "Azithral 500", "severity": "moderate",
        "title": "Possible muscle-related effects",
        "description": "Azithromycin may raise the risk of statin-related muscle pain (myopathy). Watch for unexplained muscle aches and tell your doctor.",
        "title_hi": "संभावित मांसपेशी-संबंधी प्रभाव",
        "description_hi": "एज़िथ्रोमाइसिन स्टैटिन-संबंधी मांसपेशी दर्द (मायोपैथी) के जोखिम को बढ़ा सकता है। अस्पष्टीकृत मांसपेशी दर्द पर ध्यान दें और अपने डॉक्टर को बताएं।",
        "title_mr": "संभाव्य स्नायू-संबंधित परिणाम",
        "description_mr": "अझिथ्रोमायसिन स्टॅटिन-संबंधित स्नायू दुखण्याचा (मायोपॅथी) धोका वाढवू शकते. अस्पष्ट स्नायू दुखण्याकडे लक्ष द्या आणि तुमच्या डॉक्टरांना सांगा.",
    },
    {
        "a": "Atorva 10", "b": "Amlong 5", "severity": "mild",
        "title": "Minor — monitor",
        "description": "Amlodipine can slightly increase atorvastatin levels. Usually fine at standard doses; report muscle pain.",
        "title_hi": "मामूली — निगरानी करें",
        "description_hi": "एम्लोडिपिन एटोरवास्टेटिन के स्तर को थोड़ा बढ़ा सकता है। सामान्य खुराक पर आमतौर पर ठीक है; मांसपेशी दर्द की सूचना दें।",
        "title_mr": "किरकोळ — लक्ष ठेवा",
        "description_mr": "अ‍ॅम्लोडिपिन अ‍ॅटोरवास्टॅटिनची पातळी थोडी वाढवू शकते. मानक डोसमध्ये सहसा ठीक असते; स्नायू दुखण्याची तक्रार करा.",
    },
    {
        "a": "Azithral 500", "b": "Amlong 5", "severity": "moderate",
        "title": "Heart-rhythm caution",
        "description": "Combination may affect heart rhythm (QT) in susceptible people. Mention any palpitations or dizziness.",
        "title_hi": "हृदय-लय सावधानी",
        "description_hi": "यह संयोजन संवेदनशील लोगों में हृदय की लय (QT) को प्रभावित कर सकता है। किसी भी धड़कन या चक्कर आने का उल्लेख करें।",
        "title_mr": "हृदय-तालाची काळजी",
        "description_mr": "हे संयोजन संवेदनशील लोकांमध्ये हृदयाच्या तालावर (QT) परिणाम करू शकते. कोणतीही धडधड किंवा चक्कर आल्यास नमूद करा.",
    },
    {
        "a": "Ecosprin 75", "b": "Warf 5", "severity": "severe",
        "title": "High bleeding risk",
        "description": "Aspirin with warfarin greatly increases bleeding risk. Use only under close medical supervision.",
        "title_hi": "उच्च रक्तस्राव जोखिम",
        "description_hi": "एस्पिरिन के साथ वारफारिन रक्तस्राव के जोखिम को बहुत बढ़ा देता है। केवल करीबी चिकित्सा निगरानी में उपयोग करें।",
        "title_mr": "उच्च रक्तस्रावाचा धोका",
        "description_mr": "अ‍ॅस्पिरिनसोबत वॉरफेरिन रक्तस्रावाचा धोका मोठ्या प्रमाणात वाढवते. फक्त जवळच्या वैद्यकीय देखरेखीखाली वापरा.",
    },
    {
        "a": "Warf 5", "b": "Voveran 50", "severity": "severe",
        "title": "Bleeding risk",
        "description": "NSAIDs like diclofenac raise the risk of bleeding when combined with warfarin.",
        "title_hi": "रक्तस्राव जोखिम",
        "description_hi": "डाइक्लोफेनाक जैसे NSAIDs वारफारिन के साथ मिलाने पर रक्तस्राव के जोखिम को बढ़ाते हैं।",
        "title_mr": "रक्तस्रावाचा धोका",
        "description_mr": "डायक्लोफेनाकसारखे NSAIDs वॉरफेरिनसोबत एकत्र केल्यास रक्तस्रावाचा धोका वाढवतात.",
    },
    {
        "a": "Ecosprin 75", "b": "Brufen 400", "severity": "moderate",
        "title": "Reduced antiplatelet effect",
        "description": "Ibuprofen can blunt aspirin's heart-protective effect. Separate the doses or ask your doctor.",
        "title_hi": "कम एंटीप्लेटलेट प्रभाव",
        "description_hi": "इबुप्रोफेन एस्पिरिन के हृदय-सुरक्षात्मक प्रभाव को कम कर सकता है। खुराकों को अलग करें या अपने डॉक्टर से पूछें।",
        "title_mr": "कमी अँटीप्लेटलेट परिणाम",
        "description_mr": "आयबुप्रोफेन अ‍ॅस्पिरिनचा हृदय-संरक्षणात्मक परिणाम कमी करू शकते. डोस वेगळे करा किंवा तुमच्या डॉक्टरांना विचारा.",
    },
    {
        "a": "Deplatt 75", "b": "Omez", "severity": "moderate",
        "title": "Reduced clopidogrel effect",
        "description": "Omeprazole may lower how well clopidogrel works. A different acid reducer may be preferred.",
        "title_hi": "कम क्लोपिडोग्रेल प्रभाव",
        "description_hi": "ओमेप्राज़ोल क्लोपिडोग्रेल के काम करने के तरीके को कम कर सकता है। एक अलग एसिड कम करने वाली दवा बेहतर हो सकती है।",
        "title_mr": "कमी क्लोपिडोग्रेल परिणाम",
        "description_mr": "ओमेप्राझोल क्लोपिडोग्रेल किती चांगले काम करते हे कमी करू शकते. वेगळी आम्ल कमी करणारी औषध पसंत केली जाऊ शकते.",
    },
    {
        "a": "Lasix 40", "b": "Voveran 50", "severity": "moderate",
        "title": "Reduced diuretic effect",
        "description": "NSAIDs can weaken furosemide and affect kidney function. Monitor if used together.",
        "title_hi": "कम मूत्रवर्धक प्रभाव",
        "description_hi": "NSAIDs फ्यूरोसेमाइड को कमज़ोर कर सकते हैं और किडनी के कार्य को प्रभावित कर सकते हैं। साथ उपयोग करने पर निगरानी रखें।",
        "title_mr": "कमी लघवीचे प्रमाण वाढवणारा परिणाम",
        "description_mr": "NSAIDs फ्युरोसेमाइड कमकुवत करू शकतात आणि किडनीच्या कार्यावर परिणाम करू शकतात. एकत्र वापरल्यास लक्ष ठेवा.",
    },
]


class Command(BaseCommand):
    help = "Seed demo medicines, alternatives and interactions."

    def handle(self, *args, **options):
        index = {}
        for data in MEDICINES:
            alternatives = data.pop("alternatives", [])
            data.setdefault("smiles", lookup_smiles(data.get("generic_name", "")))
            med, _ = Medicine.objects.update_or_create(name=data["name"], defaults=data)
            index[med.name] = med
            for alt in alternatives:
                GenericAlternative.objects.get_or_create(
                    medicine=med, name=alt["name"], defaults=alt
                )

        for item in INTERACTIONS:
            a, b = index.get(item["a"]), index.get(item["b"])
            if a and b:
                DrugInteraction.objects.update_or_create(
                    medicine_a=a,
                    medicine_b=b,
                    defaults={
                        "severity": item["severity"],
                        "title": item["title"],
                        "description": item["description"],
                        "title_hi": item["title_hi"],
                        "description_hi": item["description_hi"],
                        "title_mr": item["title_mr"],
                        "description_mr": item["description_mr"],
                    },
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {Medicine.objects.count()} medicines, "
                f"{GenericAlternative.objects.count()} alternatives, "
                f"{DrugInteraction.objects.count()} interactions."
            )
        )
