# Generated by Django 5.1.4 on 2026-06-29 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='medicines.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('medicine_a', 'medicine_b')},
            },
        ),
    ]
