# Generated by Django 5.1.4 on 2026-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="druginteraction",
            name="description_hi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="description_mr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="title_hi",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="title_mr",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
