# Generated by Django 5.1.4 on 2026-06-29 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('speciality', models.CharField(blank=True, max_length=255)),
                ('clinic', models.CharField(blank=True, max_length=255)),
                ('prescribed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='ready', max_length=20)),
                ('source', models.CharField(choices=[('scan', 'Scan'), ('camera', 'Camera'), ('pdf', 'PDF'), ('manual', 'Manual')], default='scan', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500 mg', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g. 1-0-1', max_length=100)),
                ('timing', models.CharField(blank=True, help_text='e.g. After food', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g. 90 days', max_length=100)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
