# Generated by Django 5.1.4 on 2026-07-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_smiles'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Auto-matched against the medicine catalog by name; null if no match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_entries', to='medicines.medicine'),
        ),
    ]
